project_id = "ypbuuvipagxfjfrhizcs"

[functions.generate-sitemap]
<<<<<<< HEAD
=======
verify_jwt = false

[functions.update-admin-password]
verify_jwt = true

[functions.verify-recaptcha]
verify_jwt = false

[functions.get-geolocation]
verify_jwt = false

[functions.get-mapbox-token]
>>>>>>> c8912d8 (Version 4 added new features and page)
verify_jwt = false
