project_id = "ypbuuvipagxfjfrhizcs"

[functions.generate-sitemap]
verify_jwt = false

[functions.update-admin-password]
verify_jwt = true

[functions.verify-recaptcha]
verify_jwt = false

[functions.get-geolocation]
verify_jwt = false

[functions.get-mapbox-token]
verify_jwt = false
